GET http://localhost:3000/language/

###

GET http://localhost:3000/language/5ecaa05bf52fa92cc8911145


###

POST http://localhost:3000/language/
Content-Type: application/json

{
    "LanguageName": "pp",
    "LanguageCode": "pp"
} 

###

PATCH http://localhost:3000/language/5ecaa05bf52fa92cc8911145
Content-Type: application/json

{
    "LanguageName": "test",
    "LanguageCode" : "hi"
} 

###

DELETE http://localhost:3000/language/5eca9c43b4cd7105e8270fbc


###

GET http://localhost:3000/category/

###

GET http://localhost:3000/category/5ec94b93c0c24e4ee40a8b57


###

POST http://localhost:3000/category/
Content-Type: application/json

{
    "CategoryName": "asdtesst"
} 

###

DELETE http://localhost:3000/category/5ec94b93c0c24e4ee40a8b57

###

PATCH http://localhost:3000/category/5ec960081df4924490c09484
Content-Type: application/json

{
    "CategoryName": "Te"
} 


###

GET http://localhost:3000/word


###

GET http://localhost:3000/word/5ec7f5208e4702176d249f5e

###

GET http://localhost:3000/word/Category/5ec584a7cef2d3b62860d3b2

